# Logger options
log_iter: 200                  # How often to log the training loss
val_iter: 100                  # How often to validate testing and save output images during training

# Optimization options
max_iter: 10000              # Maximum number of training iterations
batch_size: 1                 # Batch size
loss: L2
optimizer: Adam               # Optimizer for trainings
weight_decay: 0.0001          # Weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.999                  # Adam parameter
lr: 0.0005                    # Initial learning rate 0.001
norm_type: MinMax             # options for normalizing the depth data [MinMax | ZScore]

################### 2D CT Image ###################
# Model options (2D CT)
mlp_type: LIIFMLP                   # Options for MLP models [LIIFMLP | depthMLP]
pos_type: IREMencoder               # Options for embedding [Oricoder | IREMencoder]
dim_for_rgb_feats: 64              # dims of image feats, set to 0 if this feat is not required
dim_for_dep_feats: 0                # dims of depth feats, set to 0 if this feat is not required

IREMencoder:
  scale: 1.0
  embedding_size:   128      # Embedding size for input Fourier feature encoding * 2
  coordinates_size: 2
  mask: true
  freq: [1.0, 3.0]
  itk: [0.1, 0.5]
#  exp_num: 3.2

LIIFMLPnet:
  mlp_hidden_list: [256, 256, 256, 256]


